# Generated by Django 5.2 on 2025-05-20 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя участника')),
                ('subscriber', models.BooleanField(blank=True, default=False, null=True, verbose_name='Подписчик')),
                ('organizer', models.BooleanField(blank=True, default=False, null=True, verbose_name='Организатор')),
                ('speaker', models.BooleanField(blank=True, default=False, null=True, verbose_name='Докладчик')),
                ('tg_id', models.BigIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Место проведения')),
            ],
        ),
        migrations.CreateModel(
            name='Donat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('donater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donats', to='bot.participant', verbose_name='Автор пожертвования')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название мероприятия')),
                ('start', models.DateTimeField(verbose_name='Дата начала')),
                ('finish', models.DateTimeField(verbose_name='Дата оконания')),
                ('speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='bot.participant', verbose_name='Докладчик')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='bot.place', verbose_name='Место проведения')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='Вопрос')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='bot.participant', verbose_name='Автор вопроса')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='bot.event', verbose_name='Доклад')),
            ],
        ),
    ]
