# Generated by Django 5.2 on 2025-05-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tg_chat_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
