# Generated by Django 5.2 on 2025-05-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_event_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100, verbose_name='Текст сообщения')),
                ('creation_date', models.DateTimeField(verbose_name='Дата создания')),
                ('send_status', models.BooleanField(default=False, verbose_name='Статус рассылки сообщения')),
                ('image', models.ImageField(upload_to='media/')),
                ('recipent', models.ManyToManyField(related_name='messages', to='bot.participant', verbose_name='Сообщения пользователю')),
            ],
        ),
    ]
