# Generated by Django 5.2 on 2025-05-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_alter_message_recipent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='recipent',
            field=models.ManyToManyField(blank=True, default=None, related_name='messages', to='bot.participant', verbose_name='Кому отправлено'),
        ),
    ]
