# Generated by Django 5.2 on 2025-05-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_alter_message_recipent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='speaker',
        ),
        migrations.AddField(
            model_name='event',
            name='speaker',
            field=models.ManyToManyField(blank=True, default=None, related_name='events', to='bot.participant', verbose_name='докладчики'),
        ),
    ]
